stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip install ruff
    - ruff check aegis/

unit-tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest aegis/tests/tools

runtime-tests:
  stage: test
  script:
    - python run_all_runtime_tests.py

# Optional placeholder
integration-tests:
  stage: test
  script:
    - echo "No integration tests defined yet"

chaos-fuzz:
  stage: test
  script:
    - python aegis/fuzz/chaos_fuzz_runner.py