# aegis/config.yaml
# Central configuration for the AEGIS framework.

# System-wide default settings.
# These values are used for any task unless overridden by a preset or a
# specific launch request.
defaults:
  # The default backend profile from backends.yaml to use if none is specified.
  backend_profile: "ollama_remote"

  # The default abstract model name.
  llm_model_name: "openchat"

  # The default maximum number of plan-execute steps an agent can take before
  # the task is automatically terminated.
  iterations: 10

  # The default timeout in seconds for waiting for a response from the LLM.
  # This should be high enough for local models to generate a complete plan.
  llm_planning_timeout: 1200

  # The default maximum number of tokens the LLM should generate for a plan.
  # This prevents the LLM from rambling and improves performance.
  max_tokens_to_generate: 1536

  # The default timeout in seconds for tool execution.
  tool_timeout: 60

  # The default safety mode. If true, tools marked as [UNSAFE] cannot be run
  # unless overridden.
  safe_mode: true

  # If the number of available tools exceeds this, a preliminary LLM call is
  # made to select a relevant subset. Set to a high number to disable.
  tool_selection_threshold: 20

# Directory paths for generated outputs.
# These paths are relative to the AEGIS project root.
paths:
  reports: "reports"
  screenshots: "reports/screenshots"
  artifacts: "artifacts"
  logs: "logs"
  index: "index"

# Configuration for RAG and agent memory.
rag:
  # The model to use for vector embeddings.
  embedding_model: "all-MiniLM-L6-v2"
  # FAISS vector index.
  index_filename: "aegis_memory.faiss"
  # Map of vector IDs to text content.
  mapping_filename: "aegis_memory_mapping.json"

# Logging configuration for the AEGIS agent itself.
logging:
  # 'debug', 'info', 'warning', 'error'.
  level: "debug"

# Centralized service URLs
services:
  redis_url: "redis://redis:6379/0"
  # This now uses an environment variable. The default is for bridge networking.
  # For host networking, set AEGIS_GUARDRAILS_URL in .env to http://localhost:12012/...
  guardrails_url: "${AEGIS_GUARDRAILS_URL:-http://nemoguardrails:8000/v1/chat/completions}"