# config.yaml
# Central configuration for the AEGIS framework.

# Directory paths for generated outputs.
# These paths are relative to the project root.
paths:
  reports: "reports"
  screenshots: "reports/screenshots"
  artifacts: "artifacts"
  logs: "logs"