# config.yaml
# Central configuration for the AEGIS framework.

# System-wide default settings.
# These can be overridden by presets and then by launch-time requests.
defaults:
  # The default backend profile to use from backends.yaml
  backend_profile: "ollama_default"
  # The default abstract model name to use (for formatter hints)
  llm_model_name: "hf.co/TheBloke/Mistral-7B-OpenOrca-GGUF:Q4_K_M"
  # The default number of steps an agent can take.
  iterations: 10
  # Maximum number of tokens the LLM should generate for a plan. This is crucial for performance.
  max_tokens_to_generate: 1024
  # The default timeout for LLM planning calls.
  llm_planning_timeout: 300
  # The default timeout for individual tool calls.
  tool_timeout: 60
  # Default safety mode. Set to false to allow unsafe tools by default.
  safe_mode: false

# Directory paths for generated outputs.
# These paths are relative to the project root.
paths:
  reports: "reports"
  screenshots: "reports/screenshots"
  artifacts: "artifacts"
  logs: "logs"
  index: "index"

# Configuration for Retrieval-Augmented Generation (RAG) and memory.
rag:
  embedding_model: "all-MiniLM-L6-v2"
  index_filename: "aegis_memory.faiss"
  mapping_filename: "aegis_memory_mapping.json"

# Logging configuration
logging:
  level: "info"