# aegis/docker-compose.yml
networks:
  bend-net:
    external: true
    name: ${AEGIS_EXTERNAL_NETWORK:-bend_bend-net}

volumes:
  aegis_ui_dist:

services:
  agent:
    env_file:
      - .env
    build: .
    container_name: agent
    ports:
      - "${AEGIS_PORT:-8000}:8000"
    networks:
      - bend-net
    # network_mode: bridge
    environment:
      - ADMIN_PASSWORD
      - ROOT_PASSWORD
      - DEPLOY_PASSWORD
      - ESXI_PASSWORD
      - LANGCHAIN_DEBUG=true
      - OTEL_SERVICE_NAME=aegis-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - BACKEND_API_KEY=${BACKEND_API_KEY}
      - GITLAB_URL
      - GITLAB_PRIVATE_TOKEN
      - SLACK_BOT_TOKEN
    restart: unless-stopped
    volumes:
      # Mount the Docker socket to allow the agent to manage containers.
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the source code directory to allow live development.
      # This is useful for development but should be removed in production.
      # - ./aegis:/app/aegis
      # The volume below preserves the built UI artifacts from the image,
      # preventing the source code mount above from hiding them.
      # - aegis_ui_dist:/app/aegis/web/react_ui/dist
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
      - ./index:/app/index
      - ./presets:/app/presets
      - ./machines.yaml:/app/machines.yaml
      - ./config.yaml:/app/config.yaml
      - ./plugins:/app/plugins
      - ./backends.yaml:/app/backends.yaml
      - ./models.yaml:/app/models.yaml
      - ./themes:/app/themes