version: "3.9"

networks:
  bend-net:
    external: true
    name: BEND_bend-net # The name is typically prefixed with the project directory name

services:
  agent:
    env_file:
      - .env
    build: .
    ports:
      - "${AEGIS_PORT:-8000}:8000"
    networks:
      - bend-net
    environment:
      - ADMIN_PASSWORD
      - ROOT_PASSWORD
      - DEPLOY_PASSWORD
      - ESXI_PASSWORD
      - LANGCHAIN_DEBUG=true
      - OTEL_SERVICE_NAME=aegis-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - BEND_API_KEY=${BEND_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
      - ./index:/app/index
      - ./presets:/app/presets
      - ./machines.yaml:/app/machines.yaml
      - ./config.yaml:/app/config.yaml
      - ./plugins:/app/plugins
      # The new backends manifest is now the source of truth for connections
      - ./backends.yaml:/app/backends.yaml
      # AEGIS needs its own models.yaml for formatter hints
      - ./aegis/models.yaml:/app/aegis/models.yaml