# aegis/docker-compose.yml
networks:
  bend-net:
    external: true
    name: ${AEGIS_EXTERNAL_NETWORK:-bend_bend-net}

volumes:
  aegis_ui_dist:

services:
  agent:
    env_file:
      - .env
    build: .
    container_name: agent
    ports:
      - "${AEGIS_PORT:-8000}:8000"
    networks:
      - bend-net
    # network_mode: bridge
    environment:
      - ADMIN_PASSWORD
      - ROOT_PASSWORD
      - DEPLOY_PASSWORD
      - ESXI_PASSWORD
      - LANGCHAIN_DEBUG=true
      - OTEL_SERVICE_NAME=aegis-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - BACKEND_API_KEY=${BACKEND_API_KEY}
      - AEGIS_POLICY_DENY_TOOLS=${AEGIS_POLICY_DENY_TOOLS:-}
      - AEGIS_POLICY_REQUIRE_APPROVAL=${AEGIS_POLICY_REQUIRE_APPROVAL:-}
      - AEGIS_POLICY_RLMAX_PER_MIN=${AEGIS_POLICY_RLMAX_PER_MIN:-0}
      - AEGIS_POLICY_ALLOW_HOSTS=${AEGIS_POLICY_ALLOW_HOSTS:-}
      - AEGIS_POLICY_ALLOW_INTERFACES=${AEGIS_POLICY_ALLOW_INTERFACES:-}
      - AEGIS_BREAKER_WINDOW_S=${AEGIS_BREAKER_WINDOW_S:-120}
      - AEGIS_BREAKER_THRESHOLD=${AEGIS_BREAKER_THRESHOLD:-3}
      - AEGIS_BREAKER_COOLDOWN_S=${AEGIS_BREAKER_COOLDOWN_S:-600}
      - AEGIS_REQUIRE_APPROVAL_GOAL_CHANGES=${AEGIS_REQUIRE_APPROVAL_GOAL_CHANGES:-}
      - AEGIS_GOAL_EDIT_REQUIRE_REASON=${AEGIS_GOAL_EDIT_REQUIRE_REASON:-}
      - AEGIS_TRACE_GENERATIONS=${AEGIS_TRACE_GENERATIONS:-1}
      - AEGIS_TRACE_SPANS=${AEGIS_TRACE_SPANS:-1}
      - AEGIS_TRACE_GENERATION=${AEGIS_TRACE_GENERATIONS:-1}
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_PRIVATE_TOKEN=${GITLAB_PRIVATE_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      # Mount the Docker socket to allow the agent to manage containers.
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the source code directory to allow live development.
      # This is useful for development but should be removed in production.
      # - ./aegis:/app/aegis
      # The volume below preserves the built UI artifacts from the image,
      # preventing the source code mount above from hiding them.
      # - aegis_ui_dist:/app/aegis/web/react_ui/dist
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
      - ./index:/app/index
      - ./presets:/app/presets
      - ./machines.yaml:/app/machines.yaml
      - ./config.yaml:/app/config.yaml
      - ./plugins:/app/plugins
      - ./backends.yaml:/app/backends.yaml
      - ./models.yaml:/app/models.yaml
      - ./themes:/app/themes