version: "3.9"
services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: ["bash", "-c", "ollama serve && sleep 2 && ollama run hf.co/Mungert/granite-3.3-8b-instruct-GGUF:Q4_K_M && wait"]
    restart: unless-stopped

  agent:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    volumes:
#      - ./reports:/app/aegis/reports
#      - ./logs:/app/aegis/logs
#      - ./machines.yaml:/app/aegis/machines.yaml
       - ./:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama-data:
