version: "3.9"
services:
  # The Ollama service has been removed from this file.
  # AEGIS now relies on the BEND stack for its LLM backend.

  agent:
    env_file:
      - .env
    build: .
    ports:
      - "${AEGIS_PORT:-8000}:8000"
    environment:
      # Environment variables are still passed for flexibility and tool use,
      # but the agent service itself no longer depends on an Ollama container.
      - OLLAMA_MODEL
      - OLLAMA_API_URL
      - OLLAMA_DIRECT_API_URL
      - KOBOLDCPP_MODEL
      - KOBOLDCPP_API_URL
      - ADMIN_PASSWORD
      - ROOT_PASSWORD
      - DEPLOY_PASSWORD
      - ESXI_PASSWORD
      - LANGCHAIN_DEBUG=true
      - OTEL_SERVICE_NAME=aegis-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - BEND_API_KEY=${BEND_API_KEY}
      - BEND_VOICE_PROXY_URL=http://voiceproxy:8001
      - BEND_RETRIEVER_URL=http://retriever:8000
    # depends_on is removed as the backend is now external in the BEND stack.
    # The wait-for-koboldcpp.sh script now handles startup dependency.
    restart: unless-stopped
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
      - ./index:/app/index
      - ./presets:/app/presets
      - ./machines.yaml:/app/machines.yaml
      - ./config.yaml:/app/config.yaml
      - ./plugins:/app/plugins
      - ./models.yaml:/app/models.yaml
    networks:
      - default

# Define the shared external network for communication with BEND
networks:
  default:
    name: aegis_bend_net
    external: true
