version: "3.9"
services:
  ollama:
    env_file:
      - .env
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama_entrypoint.sh:/app/ollama_entrypoint.sh
    environment:
      - OLLAMA_MODEL
    ports:
      - "11434:11434"
    entrypoint: ["bash", "/app/ollama_entrypoint.sh"]
    restart: unless-stopped

  agent:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment: 
      - OLLAMA_MODEL
      - OLLAMA_HOST
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama-data:
