# aegis/docker-compose.yml
version: "3.9"

networks:
  bend-net:
    external: true
    name: ${BEND_NETWORK_NAME:-bend_bend-net} # Use variable, with a default

services:
  agent:
    env_file:
      - .env
    build: .
    container_name: agent
    ports:
      - "${AEGIS_PORT:-8000}:8000"
    networks:
      - bend-net
    environment:
      - ADMIN_PASSWORD
      - ROOT_PASSWORD
      - DEPLOY_PASSWORD
      - ESXI_PASSWORD
      - LANGCHAIN_DEBUG=true
      - OTEL_SERVICE_NAME=aegis-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - BEND_API_KEY=${BEND_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      # Explicitly define the path to the model manifest inside the container
      - MODEL_MANIFEST_PATH=/app/models.yaml
    restart: unless-stopped
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
      - ./index:/app/index
      - ./presets:/app/presets
      - ./machines.yaml:/app/machines.yaml
      - ./config.yaml:/app/config.yaml
      - ./plugins:/app/plugins
      - ./backends.yaml:/app/backends.yaml
      - ./models.yaml:/app/models.yaml
      - ./themes:/app/themes