# presets/default.yaml
name: "Default Agent Flow (KoboldCPP Backend)"
description: "A basic agent flow that plans, executes, and then decides to loop or end, using the BEND KoboldCPP backend."
state_type: "aegis.agents.task_state.TaskState"
entrypoint: "plan"

nodes:
  - id: "plan"
    tool: "reflect_and_plan"
  - id: "execute"
    tool: "execute_tool"
  - id: "summarize"
    tool: "summarize_result"

edges:
  - [ "plan", "execute" ]
  - [ "summarize", "__end__" ]

condition_node: "execute"
condition_map:
  continue: "plan"
  end: "summarize"

runtime:
  llm_backend_type: "koboldcpp"
  llm_model_name: "hermes" # Key from BEND's models.yaml
  koboldcpp_api_url: "http://koboldcpp:12009/api/v1/generate"
  ollama_api_url: null
  llm_planning_timeout: 300
  temperature: 0.2
  max_context_length: 4096
  max_tokens_to_generate: 1536
  top_p: 0.9
  top_k: 40
  repetition_penalty: 1.1
  safe_mode: true
  tool_timeout: 60
  tool_retries: 0
  iterations: 10