# presets/default.yaml
# A basic agent flow that plans, executes, and then decides to loop or end.
# It inherits most of its runtime configuration from the system-wide
# defaults specified in config.yaml.
name: "Default Agent Flow"
description: "A basic agent flow that plans, executes, and then decides to loop or end."
state_type: "aegis.agents.task_state.TaskState"
entrypoint: "plan"

nodes:
  - id: "plan"
    tool: "reflect_and_plan"
  - id: "execute"
    tool: "execute_tool"
  - id: "summarize"
    tool: "summarize_result"

edges:
  - [ "plan", "execute" ]
  - [ "summarize", "__end__" ]

condition_node: "execute"
condition_map:
  continue: "plan"
  end: "summarize"

# For this preset, there are no overrides, so it's empty.
runtime: {}