# presets/default.yaml
# This file defines the default agent behavior using a LangGraph structure.

# The class path to the main state object for this graph.
state_type: "aegis.agents.task_state.TaskState"

# The first node to be executed when the graph starts.
entrypoint: "plan"

# A list of all the nodes (functions) that make up the graph.
# The `tool` name here refers to the key in `aegis.agents.node_registry.AGENT_NODE_REGISTRY`.
nodes:
  - id: "plan"
    tool: "reflect_and_plan"
  - id: "execute"
    tool: "execute_tool"
  - id: "check_termination"
    tool: "check_termination"
  - id: "summarize"
    tool: "summarize_result"

# Defines the unconditional transitions between nodes.
edges:
  - [ "plan", "execute" ]
  - [ "execute", "check_termination" ]
  - [ "summarize", "__end__" ] # After summarizing, the graph always ends.

# Defines the node that will make a routing decision.
condition_node: "check_termination"

# Defines the possible outcomes from the condition_node and where to go next.
# The `check_termination` function will return either 'continue' or 'end'.
condition_map:
  continue: "plan"      # If we continue, loop back to the planning step.
  end: "summarize"  # If we end, go to the summarization step before finishing.